### ISSUE TITLE
Bert Qa Kotlin sample

### ISSUE THREAD

**Issue by SunitRoy2703** [SunitRoy2703/Tensorflow-lite-kotlin-samples#2]
- Understanding [TFLite Bert Qa sample app](https://github.com/SunitRoy2703/examples/tree/1273c41c66ff38cec3023f7383f74db34f8b8eaa/lite/examples/bert_qa/android) in JAVA
- Rewriting TFLite Bert Qa sample app in Kotlin with only Task Library Implementation 
-  Rewriting tests in kotlin is not mandatory but is recommended 

TFLite Bert Qa sample app in java for reference: https://github.com/SunitRoy2703/examples/tree/1273c41c66ff38cec3023f7383f74db34f8b8eaa/lite/examples/bert_qa/android

**Comment by dhruvnagarajan** [comment]
Need a separate kotlin version or conversion?
