### ISSUE TITLE
New TFLite sample(kotlin)

### ISSUE THREAD

**Issue by SunitRoy2703** [SunitRoy2703/Tensorflow-lite-kotlin-samples#3]
- if you have a TFLite sample app, which is not present in this repo and you want to contribute, then you can take this issue
- sample app must written in Kotlin 
- app also should use TFLite

join our discord if you have queries: https://discord.gg/SBRfdXs7qD

**Comment by dhruvnagarajan** [comment]
Hi @SunitRoy2703 I can see 'recommendation' in upcoming models in the readme. Are you working on it? What type of recommendations are you thinking?

**Comment by SunitRoy2703** [comment]
Hey @dhruvnagarajan, I'm not working on the recommendation sample for now if you want you can start with it.

the recommendation sample will be the kotlin version of the [recommendation sample](https://github.com/tensorflow/examples/tree/master/lite/examples/recommendation/android) in [Tensorflow Lite Examples](https://github.com/tensorflow/examples/tree/master/lite/examples)

you can learn more about the recommendation sample here: https://www.tensorflow.org/lite/examples/recommendation/overview#examples

**Comment by dhruvnagarajan** [comment]
ok @SunitRoy2703 cool i'll take care of this
